---
Dev_Mode: false
Server-Name-Dev: CR
Server-Name: CR
Hub-Command: §bGoing Back to Hub..
Unknown-Command: §cUnknown command. Try /help for a list of commands
max-caps: 3
interval: 10
item1: 111
item2: 111
item3: 111
item4: 111
...
